import type { Metadata } from "next";
import "./globals.css";
import MenuBar from "@/components/menu bar/MenuBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </head>
      <body className="min-h-screen flex flex-col">
        <main className="flex-grow">{children}</main>
        <MenuBar />
      </body>
    </html>
  );
}
